apiVersion: apps/v1
kind: Deployment
metadata: 
  name: apache2-deployment
spec:
  selector:
    matchLabels: 
      app: apache2
  replicas: 2
  template: 
    metadata: 
      labels: 
        app: apache2
    spec:
      containers: 
      - name: apache2
        image: apahce2: 2.4.59-2
	ports:
 	- containerPort: 80
