apiVersion: apps/v1
kind: Deployment
metadata: 
  name: apache2
spec:
  selector:
    matchLabels: 
      app: apache2
  replicas: 2
  template: 
    metadata: 
      labels: 
        app: apache2
    spec:
      containers: 
      - name: apache2
        image: apahce: 2.2.20
	ports:
 	- containerPort: 443
